import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import os
import glob

st.set_page_config(page_title="Grid Anomaly & Load Forecasting", page_icon="⚡", layout="wide")

st.title("⚡ Grid Anomaly & Load Forecasting Dashboard")
st.markdown("""
Welcome to the interactive dashboard for the **CSE412 Big Data Applied Project**. 
This app visualizes the outputs generated by our HDFS -> Pig -> Hive -> Spark MLlib pipeline.
""")

# Load Data
@st.cache_data
def load_data():
    data = {}
    try:
        data['overall'] = pd.read_csv('results/forecast_metrics_overall.csv')
        data['hourly'] = pd.read_csv('results/forecast_metrics_by_hour.csv')
        data['acorn'] = pd.read_csv('results/forecast_metrics_by_acorn.csv')
        data['tariff'] = pd.read_csv('results/forecast_metrics_by_tariff.csv')
        data['reporting'] = pd.read_csv('results/reporting_output.csv')
    except Exception as e:
        st.warning(f"Could not load some CSVs. Have you run the pipeline? Error: {e}")
    return data

data = load_data()

tab1, tab2, tab3 = st.tabs(["📊 Forecasting Performance", "🏘️ Consumer Reporting", "🚨 Anomaly Detection"])

with tab1:
    st.header("Forecasting Metrics")
    if 'overall' in data:
        st.subheader("Overall Model Performance vs Baselines")
        st.dataframe(data['overall'], use_container_width=True)
    
    col1, col2 = st.columns(2)
    with col1:
        if 'hourly' in data:
            st.subheader("RMSE by Hour of Day")
            hourly = data['hourly'].sort_values('hour')
            st.line_chart(hourly.set_index('hour')['model_rmse'])
    
    with col2:
        if 'tariff' in data:
            st.subheader("Performance by Tariff (Standard vs ToU)")
            st.bar_chart(data['tariff'].set_index('tariff')['model_rmse'])

with tab2:
    st.header("Consumer Group Insights (Acorn)")
    if 'reporting' in data:
        st.dataframe(data['reporting'], use_container_width=True)
        # Assuming there's a column for acorn group and avg consumption or similar
        # Will display raw data for now as exact schema of reporting_output.csv isn't known
        st.info("Hive Aggregations output displayed above.")

with tab3:
    st.header("Anomaly Detection (Residual & K-Means)")
    
    col1, col2 = st.columns([1, 2])
    with col1:
        st.subheader("Detector Metrics")
        try:
            with open('results/anomaly_metrics.txt', 'r') as f:
                metrics = f.read()
            st.code(metrics, language="text")
        except:
            st.warning("Anomaly metrics not found.")
            
    with col2:
        st.subheader("Example Anomalies Identified")
        if os.path.exists('results/detector_A_example.png'):
            st.image('results/detector_A_example.png', caption="Detector A Output", use_column_width=True)
        else:
            st.warning("Detector plot not found.")
